/*
  # Create KPIs table

  1. New Tables
    - `kpis`
      - `id` (bigint, primary key, auto-generated)
      - `metric_name` (text, required) - Name of the KPI metric
      - `value` (numeric, required) - The KPI value
      - `date` (date, required) - Date for the KPI measurement
      - `source` (text, required) - Source of the KPI data
      - `created_at` (timestamptz, default now()) - Record creation timestamp

  2. Security
    - Enable RLS on `kpis` table
    - Add policy for authenticated users to read KPI data

  3. Sample Data
    - Insert sample KPI data for testing and demonstration
*/

CREATE TABLE IF NOT EXISTS kpis (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  metric_name TEXT NOT NULL,
  value NUMERIC NOT NULL,
  date DATE NOT NULL,
  source TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE kpis ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read kpis"
  ON kpis
  FOR SELECT
  TO authenticated
  USING (true);

-- Insert sample KPI data
INSERT INTO kpis (metric_name, value, date, source) VALUES
  ('Website Traffic', 15420, '2024-01-15', 'Google Analytics'),
  ('Conversion Rate', 3.2, '2024-01-15', 'Google Analytics'),
  ('Average Session Duration', 245, '2024-01-15', 'Google Analytics'),
  ('Bounce Rate', 42.5, '2024-01-15', 'Google Analytics'),
  ('Social Media Followers', 2850, '2024-01-15', 'Social Media APIs'),
  ('Email Subscribers', 1240, '2024-01-15', 'Email Platform'),
  ('Customer Satisfaction', 4.6, '2024-01-15', 'Survey Platform'),
  ('Revenue', 28500, '2024-01-15', 'Sales System'),
  ('Website Traffic', 16200, '2024-01-14', 'Google Analytics'),
  ('Conversion Rate', 3.4, '2024-01-14', 'Google Analytics'),
  ('Average Session Duration', 252, '2024-01-14', 'Google Analytics'),
  ('Bounce Rate', 41.8, '2024-01-14', 'Google Analytics'),
  ('Social Media Followers', 2835, '2024-01-14', 'Social Media APIs'),
  ('Email Subscribers', 1235, '2024-01-14', 'Email Platform'),
  ('Customer Satisfaction', 4.5, '2024-01-14', 'Survey Platform'),
  ('Revenue', 27800, '2024-01-14', 'Sales System');